[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.2"  # LTS version
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

[context.production]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  
[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

# Environment variables - set these in Netlify UI
# [build.environment]
#   VITE_GEMINI_API_KEY = "your-gemini-api-key-here"
#   GEMINI_API_KEY = "your-gemini-api-key-here"
