[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"  # LTS version
  NPM_FLAGS = "--legacy-peer-deps"

# Environment variables - set these in Netlify UI
# [build.environment]
#   VITE_GEMINI_API_KEY = "your-gemini-api-key-here"
#   GEMINI_API_KEY = "your-gemini-api-key-here"
